FROM        amazoncorretto:21

# Metadata
LABEL       author="Lovinoes" maintainer="lovinoes@lovinoes.de"
LABEL       org.opencontainers.image.source="https://github.com/lovinoes/images"
LABEL       org.opencontainers.image.licenses="MIT"
LABEL       org.opencontainers.image.title="java21_corretto"
LABEL       org.opencontainers.image.description="Amazon Corretto (JDK 21) image."

# Install necessary packages
RUN         yum upgrade -y \
            && yum install -y ca-certificates openssl tar sqlite fontconfig freetype freetype-devel lsof tzdata iproute \
            git gcc gcc-c++ automake make libtool \
            && yum clean all \
            && rm -rf /var/cache/yum \
            && useradd -m -d /home/container container

# Set locale and language environment variables
ENV         LC_ALL=en_US.UTF-8
ENV         LANG=en_US.UTF-8
ENV         LANGUAGE=en_US.UTF-8

# Copy the entrypoint script
USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

# Set the entrypoint command
COPY        ./entrypoint.sh /entrypoint.sh
CMD         [ "/bin/bash", "/entrypoint.sh" ]
