name: build java_temurin

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *" # bi-weekly on 1st and 15th calendar day at 17:00
  push:
    branches:
      - main
    paths:
      - java-temurin/**

permissions:
  actions: read
  packages: write

concurrency:
  group: java-temurin-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build_and_push:
    name: "java${{ matrix.tag }}_temurin"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 8
          - 11
          - 17
          - 21
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v4

      - name: Setup QEMU for multiarch builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./java-temurin
          platforms: linux/amd64, linux/arm64
          file: ./java-temurin/${{ matrix.tag }}/Dockerfile
          push: true
          tags: ghcr.io/lovinoes/images:java-temurin${{ matrix.tag }}_temurin
          
